@startuml

scale max 340 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #RoyalBlue   
skinparam ArrowFontColor #RoyalBlue   
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment right
skinparam BoxPadding 10
skinparam ClassFontSize 16
skinparam ClassFontStyle bold
skinparam ClassStereotypeFontSize 16
skinparam dpi 300
skinparam FooterFontSize 14
skinparam FooterFontStyle italic
skinparam LegendBackgroundColor #Snow
skinparam LegendFontName Helvetica
skinparam LegendFontSize 16
skinparam linetype ortho
skinparam nodesep 35
skinparam NoteBackgroundColor #LightYellow
skinparam NoteFontSize 15
skinparam NoteTextAlignment left
skinparam ranksep 40
skinparam roundcorner 5
skinparam TitleFontSize 20



title "Shared Digital Health Record - FHIR data model"

frame "Core Data Services" as SDHRFrame {

' class "SDHR:Encounter" as encounter <<Encounter>> #LightSalmon ##[bold] {
'     Represents a SDHR encounter
'     [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHREncounter.html]]
'     Inherits FHIR ""Encounter""
'     ----
'     * **meta.source**: ~~1..1~~ "https://api.hip.digital.health.nz/fhir/hpi/v1/Location/{hpi-facilityid}}"
'     * **meta.profile**: ~~1..1~~ "https://fhir-ig.digital.health.nz/sdhr/StructureDefinition/SDHREncounter"
'     * **status**: ~~1..1~~ Binding: EncounterStatus [[[http://hl7.org/fhir/R4/valueset-encounter-status.html]]]
'     * **class**: ~~1..1~~ Binding: ActEncounterCode (extensible) [[[http://terminology.hl7.org/5.5.0/ValueSet-v3-ActEncounterCode.html]]]
'     * **subject**: ~~1..1~~ Reference NHI Patient
'     * **participant.individual**: ~~1..1~~ Reference Practitioner
' }

class "SDHR:Condition" as condition <<Condition>> #LightSalmon ##[bold] {
    Represents a SDHR condition
    [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHRCondition.html SDHR profile]]
    Inherits FHIR ""Condition""
    ----
    * **meta.source**: ~~1..1~~ HPI Location
    * **code**: ~~1..1~~ Condition or diagnosis code
    * **subject**: ~~1..1~~ Reference NHI Patient
    * **clinicalStatus**: ~~0..1~~ Clinical status
    * **verificationStatus**: ~~0..1~~ Verification status
    * **onsetDateTime**: ~~0..1~~ Onset date
    * **recorder | asserter**: Reference Practitioner
}

class "SDHR:AllergyIntolerance" as allergyintolerance <<AllergyIntolerance>> #LightSalmon ##[bold] {
    Represents a SDHR allergy intolerance
    [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHRAllergyIntolerance.html SDHR profile]]
    Inherits FHIR ""AllergyIntolerance""
    ----
    * **meta.source**: ~~1..1~~ HPI Location
    * **clinicalStatus**: ~~1..1~~ Clinical status
    * **verificationStatus**: ~~1..1~~ Verification status
    * **code**: ~~1..1~~ Allergy or intolerance code
    * **patient**: ~~1..1~~ Reference NHI Patient
    * **category**: ~~0..*~~ Allergy category
    * **recorder**: ~~0..1~~ Reference Practitioner
}

class "SDHR:Observation" as observation <<Observation>> #LightSalmon ##[bold] {
    Represents a SDHR observation
    [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHRObservation.html SDHR profile]]
    Inherits FHIR ""Observation""
    ----
    * **meta.source**: ~~1..1~~ HPI Location
    * **code**: Observation code
    * **subject**: ~~1..1~~ Reference NHI Patient
    * **effectiveDateTime**: Observation date
    * **value[x]**: Observation value
    * **interpretation**: Result interpretation
    * **status**: Observation status
    * **performer**: Reference Practitioner
}

class "SDHR:MedicationRequest" as medicationrequest <<MedicationRequest>> #LightSalmon ##[bold] {
    Represents prescribing intent from MDR
    [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHRMedicationRequest.html SDHR profile]]
    Inherits FHIR ""MedicationRequest""
    ----
    * **id**: MDR prescription item identifier
    * **identifier**: NZePS prescription item ID
    * **status**: ~~1..1~~ Medication request status
    * **medicationCodeableConcept**: ~~1..1~~ Medication requested
    * **subject**: ~~1..1~~ Reference NHI Patient
    * **authoredOn**: ~~0..1~~ Date and time authored
    * **requester**: ~~0..1~~ Reference Practitioner or Organization
    * **reasonReference**: ~~0..*~~ Reference Condition or Observation
}

class "SDHR:MedicationDispense" as medicationdispense <<MedicationDispense>> #LightSalmon ##[bold] {
    Represents medicines supplied from MDR
    [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHRMedicationDispense.html SDHR profile]]
    Inherits FHIR ""MedicationDispense""
    ----
    * **id**: ~~1..1~~ MDR dispense record identifier
    * **identifier**: ~~1..1~~ NZePS prescription item ID
    * **status**: ~~1..1~~ completed
    * **authorizingPrescription**: ~~0..*~~ Reference MedicationRequest
    * **subject**: ~~1..1~~ Reference NHI Patient
    * **quantity**: ~~0..1~~ Quantity dispensed
    * **daysSupply**: ~~0..1~~ Expected days supplied
    * **whenHandedOver**: ~~0..1~~ Date and time supplied
    * **destination**: ~~0..1~~ Reference Location
}

class "SDHR:Immunization" as immunization <<Immunization>> #LightSalmon ##[bold] {
    Represents an immunisation event from AIR
    [[https://fhir-ig.digital.health.nz/sdhr/StructureDefinition-SDHRImmunization.html SDHR profile]]
    Inherits AIR ""Immunization""
    ----
    * **id**: ~~1..1~~ Immunisation event identifier
    * **status**: ~~1..1~~ Immunisation event status
    * **vaccineCode**: ~~1..1~~ Vaccine administered
    * **patient**: ~~1..1~~ Reference NHI Patient
    * **occurrence[x]**: ~~1..1~~ Date or timing of the event
    * **location**: ~~0..1~~ Reference Location
    * **performer**: ~~1..*~~ Reference Practitioner or Organization
}


frame "Te Whatu Ora NHI/HPI" as NationalIdentifier {

  class "Patient (NHI)" as Patient <<Reference>> #SkyBlue {
    * logical id: NHI
  }

  class "HPI" as HPI <<Reference>> #SkyBlue {
    org identifier format
      ""GXXNNN-C"" HPI Org Id
  }

  Patient -[hidden]l- HPI
}

rectangle "Notes" as Notes {
    note as N1
    **Notes**
    The following resources are sourced from primary care systems:
    - AllergyIntolerance
    - Condition
    ' - Encounter
    - Observation
    The following resources are existing national data services:
    - Immunization (AIR)
    - Patient (NHI)
    - Practitioner/Organization/Location (HPI)
    - MedicationRequest/MedicationDispense (MDR)
  }
end note
}
}

' ********
' * Entities outside any frame are in other bounded contexts


' ********
' plantuml positioning

' ********
' * layout

condition -[hidden]right- allergyintolerance
allergyintolerance -[hidden]right- observation
medicationrequest -[hidden]right- medicationdispense
medicationdispense -[hidden]right- immunization
condition -[hidden]down- medicationrequest
allergyintolerance -[hidden]down- medicationdispense
observation -[hidden]down- immunization

' ********
' * resource linkages

' encounter "subject" -[#SkyBlue,dashed]up-- Patient
' encounter "participant" -[#SkyBlue,dashed]up-- HPI
condition "subject" -[#SkyBlue,dashed]down-- Patient
condition "recorder | asserter" --[#SkyBlue,dashed]down-- HPI
allergyintolerance "subject" -[#SkyBlue,dashed]up-- Patient
allergyintolerance "recorder" -[#SkyBlue,dashed]up-- HPI
observation "subject" -[#SkyBlue,dashed]down-- Patient
observation "performer" --[#SkyBlue,dashed]down-- HPI
medicationrequest "subject" -[#SkyBlue,dashed]down-- Patient
medicationrequest "requester | supporting information" --[#SkyBlue,dashed]down-- HPI
medicationdispense "subject" -[#SkyBlue,dashed]up-- Patient
medicationdispense "destination" --[#SkyBlue,dashed]up-- HPI
medicationdispense "authorizing prescription" -[#RoyalBlue,dashed]up-- medicationrequest
immunization "patient" -[#SkyBlue,dashed]down-- Patient
immunization "location | performer" --[#SkyBlue,dashed]down-- HPI
Notes -[hidden]left- Patient

'NationalIdentifier -[hidden]- SDHRFrame

legend right
  **Notes**
  - (preferred) indicates that whilst not mandatory it highly desirable.
  '- Arrows show direction of FHIR reference.
  '- Solid/open bullets indicate mandatory/optional data elements.

  **Key to datatype colours**
  |= colour |= stereotype |
  | <back:#GhostWhite>ghost white\n | Standard FHIR resource in TWO IG |
  | <back:#LightSalmon>salmon\n | Profiled FHIR resource |
  | <back:#OrangeRed>orange red\n | Canonical shared resource defined by TWO |
  | <back:#SkyBlue>sky blue\n| Logical identifier reference to records in national systems |
endlegend

footer "Health NZ/Te Whatu Ora.  Generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml
