@startuml

title SDHR Participate Operation PMS Opt Off Sequence Diagram

autonumber "<color:Black>[00]"

skinparam ActorFontSize 16
skinparam ArrowFontSize 12
skinparam ArrowFontSize 16
skinparam BoxPadding 5
skinparam DatabaseFontSize 16
skinparam dpi 400
skinparam EntityFontSize 16
skinparam MaxMessageSize 375
skinparam NoteFontSize 14
skinparam ParticipantFontSize 16
skinparam ParticipantPadding 5
skinparam responseMessageBelowArrow true
skinparam roundcorner 15
skinparam sequenceArrowThickness 2
skinparam SequenceBoxFontSize 16
skinparam sequencegroupfontsize 14
skinparam SequenceMessageAlignment left
skinparam sequenceStyle uml2
skinparam TitleFontSize 20
' semi-transparent sequence groups!
' see https://sarafian.github.io/tips/2021/03/11/plantuml-tips-tricks-1.html#:~:text=responseMessageBelowArrow-,Semi,-transparent%20group%20backgrounds
skinparam SequenceGroupBodyBackgroundColor #EEEEFF50

scale max 400 width
scale 300*500

actor "Health Practitioner" as USER
participant "PMS" as APIC #Orange
participant "PMS Orchestrator" as ORCHESTRATOR #Orange
control "Participate Operation\n$participate" as PARTICIPATE #LightBlue
control "SDHR FHIR API" as FHIRAPI #LightBlue
database "SDHR FHIR Server" as SDHR #LightGreen

== Patient opts out of SDHR participation ==
USER -> APIC : Request to opt out\nof SDHR participation
APIC -> ORCHESTRATOR : Trigger patient event
ORCHESTRATOR -> APIC : Retrieve patient details
ORCHESTRATOR -> ORCHESTRATOR : Prepare participation\nparameters
ORCHESTRATOR -> PARTICIPATE : Invoke participate operation
note left of PARTICIPATE
  Parameters:
  - patient: Patient ID
  - facilityId: Facility ID
  - participationIndicator: false
  - reasonCode: sdhr-participation
end note
PARTICIPATE -> FHIRAPI : Write Participation
FHIRAPI -> SDHR : Persist
PARTICIPATE -> ORCHESTRATOR : Return OperationOutcome

==Optional==
ORCHESTRATOR -> FHIRAPI : Search Resource (e.g. Condition)
FHIRAPI -> SDHR : Query Resource
SDHR -> FHIRAPI : Return
FHIRAPI -> ORCHESTRATOR : Return Search result with REDACTED data
note right of ORCHESTRATOR
  "meta" : {
    "security" : [
      {
        "system" : "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
        "code" : "redacted",
        "display" : "REDACTED"
      }
    ]
  },
  "type" : "searchset",
  "total" : 2,
  "entry": []
end note

==Optional==
ORCHESTRATOR -> FHIRAPI : GET **ANY** Resource by ID (e.g. /Condition/{ID})
FHIRAPI -> SDHR : Query Resource by ID
SDHR -> FHIRAPI : Return 403
FHIRAPI -> ORCHESTRATOR : Return OperationOutcome UNAUTHORIZED
note right of ORCHESTRATOR
  "resourceType" : "OperationOutcome",
  "issue" : [
    {
      "severity" : "error",
      "code" : "forbidden",
      "details" : {
        "text" : "Access to the resource is forbidden due to patient participation preferences."
      }
    }
  ]
end note

@enduml