@startuml

autonumber "<color:Black>[00]"

skinparam ActorFontSize 16
skinparam ArrowFontSize 12
skinparam ArrowFontSize 16
skinparam BoxPadding 5
skinparam DatabaseFontSize 16
skinparam dpi 400
skinparam EntityFontSize 16
skinparam MaxMessageSize 375
skinparam NoteFontSize 14
skinparam ParticipantFontSize 16
skinparam ParticipantPadding 5
skinparam responseMessageBelowArrow true
skinparam roundcorner 15
skinparam sequenceArrowThickness 2
skinparam SequenceBoxFontSize 16
skinparam sequencegroupfontsize 14
skinparam SequenceMessageAlignment left
skinparam sequenceStyle uml2
skinparam TitleFontSize 20
' semi-transparent sequence groups!
' see https://sarafian.github.io/tips/2021/03/11/plantuml-tips-tricks-1.html#:~:text=responseMessageBelowArrow-,Semi,-transparent%20group%20backgrounds
skinparam SequenceGroupBodyBackgroundColor #EEEEFF50

@enduml